Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /api/consultations/create/
Not Found: /api/process_payment/
Not Found: /api/process_payment/
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/process_payment/
C:\Users\hp\ai_consultation\payments\views.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/process_payment/
Unauthorized: /api/process_payment/
Unauthorized: /api/process_payment/
Unauthorized: /api/process_payment/
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/process_payment/
Unauthorized: /api/process_payment/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /consultation/user/signup/
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /api/users/
Not Found: /api/consultations/
Not Found: /api/consultations/1/
C:\Users\hp\ai_consultation\consultation\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/consultations/1/
Watching for file changes with StatReloader
Not Found: /api/users/
C:\Users\hp\ai_consultation\consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Internal Server Error: /api/v1/consultations
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/consultations/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/v1/
Watching for file changes with StatReloader
Not Found: /api/consultations/
Not Found: /api/consultations/
Watching for file changes with StatReloader
Not Found: /api/signup
Not Found: /api/signup
Not Found: /api/signup/
Not Found: /api/signup/
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /api/consultations/
Not Found: /api/consultations/
C:\Users\hp\ai_consultation\consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\consultation\models.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/v1/create/
Unauthorized: /api/v1/list/
Unauthorized: /api/v1/create/
Unauthorized: /api/v1/list/
Internal Server Error: /api/v1/create/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /api/users/
Not Found: /api/consultations/
Not Found: /api/consultations/
Not Found: /api/consultations/
Not Found: /api/consultations/
Not Found: /api/consultations/
Not Found: /api/consultations/
Not Found: /api/consultations/
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\hp\ai_consultation\ai_consultation\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
